language: ruby
rvm:
- 2.3.1
addons:
  postgresql: '9.3'
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:migrate RAILS_ENV=test
script: bundle exec rake fspec
deploy:
  provider: heroku
  api_key:
    secure: "Ao70RwOTMe0D6Fxh0S0JclxJUDlYrXHqTdffS2z9ws89xeexft4Yzrh0T5CnnvXL4trOFfqeZHMFccIGUpAHb64FWwweSq77rvdG8nW7VRzGOO/KFg6WKQva98WYYVl7vo56AgNEXjxBVMr6Ea8/VneNap9ydhDP9lrqdnf5xms="
  app: sup-production
  on:
    repo: artsy/sup
